# Generated by Django 3.2.4 on 2021-08-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(max_length=1000)),
                ('is_seen', models.BooleanField(default=False)),
                ('reciver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_name', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
