# Generated by Django 3.2.4 on 2021-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
