# Generated by Django 3.2.4 on 2021-06-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.friend'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.group'),
        ),
    ]
